<?php $collection = $this->getFeaturedPosts();
 if ($block->isModuleEnabled() == true && $block->enableHomepage() == 1 ){?>
<div class="content-heading">
   <h2 class="title review-title"><?php echo $block->homepageSliderText(); ?></h2>
</div>

<div id="testimonial-slider" class="owl-carousel">
    <?php
    foreach ($collection as $item){?>
        <div class="testimonial-12">
            <div class="testimonial-content">
            <div class="testimonial-icon">
            <i class="fa fa-quote-left"></i>
            </div>
            <p class='description'><?php echo $item->getContent()?></p>
            </div>
            <?php if ($this->enableStar() == 1) {?>
            <ul class="rating">
              <?php
              if (!empty ($item->getRating()))
              {
                for ($i = 0 ; $i < (int)$item->getRating() ; $i++)
                {
                    echo "<li class='fa fa-star'></li>";
                }
              }
              ?>
            </ul>
        <?php } ?>
            <?php if (strlen($item->getNickName()) > 30)
            {
                $stringCut = substr($item->getNickName(), 0, 20);
                echo  __("<h3 class='title'>".$stringCut."</h3>");
            }
            else
            {
                echo  "<h3 class='title'>".$item->getNickName()."</h3>";
            }
            ?>
             <?php if ($this->enablePosition() == 1) {?>
            <span class="post"><?php echo $item->getJob(); ?></span>
            <?php }?>
              <?php if ($this->enableSocial() == 1) {?>
            <ul class="social-links">
                <?php if (!empty($item->getTwitter()))
                {
                    echo "<li><a href=".$item->getTwitter()."  target='_blank' class='fab fa-twitter'></a></li>";
                }
                if (!empty($item->getFacebook()))
                {
                    echo "<li><a href=".$item->getFacebook()." target='_blank' class='fab fa-facebook-f'></a></li>";
                }
                if (!empty($item->getLinkedin()))
                {
                    echo "<li><a href=".$item->getLinkedin()." target='_blank' class='fab fa-linkedin'></a></li>";
                }
                if (!empty($item->getYoutube()))
                {
                    echo "<li><a href=".$item->getYoutube()." target='_blank' class='fab fa-youtube'></a></li>";
                }
                if (!empty($item->getVimeo()))
                {
                    echo "<li><a href=".$item->getVimeo()." target='_blank' class='fab fa-vimeo'></a></li>";
                }

                ?>
            </ul>
            <?php } ?>
        </div>
    <?php  } ?>
</div>
<?php } ?>
