<!-- grid template -->
<?php
$baseUrl= $this->getBaseUrl();
$ConfigUrl  = $this->getConfigUrl();
$mediaUrl = $ConfigUrl . '/pub/media/testimonials/';
echo $this->getThumbnail();
?>
<?php $collection = $this->getPosts();
?>
  <div class="container-testimonial">
  <div class="b-title">
      <h2 class="testimonial-title"><?php echo $block->headTextforListing(); ?></h2>
  </div>
  <div class="add-new">
      <a href="../testimonials/form"><button class="button">Add testimonials</button></a>
  </div>
  </div>
  <div class="clearfix"></div>
  <div class="container" >
    <?php
    $count = 1;
    foreach ($collection as $item){?>
        <div class="testimonial-6 col-4 testimonial-content">
         <?php if(!empty($item->getAvatar())){
            $postImage= $block->resize($item->getAvatar(),111.6,111.6);
            echo '<div class="pic"> <img src='.$postImage.'> </div>';
          }else{
            echo '<div class="pic"> <img src='.$block->getPlaceHolderImage().'> </div>';
            } ?>
           <p class='description'><?php echo $item->getContent()?></p>
           <div class="absolute-div">
   <?php if ($this->enableStar() == 1) {?>
            <ul class="rating">
              <?php
              if (!empty ($item->getRating()))
              {
                for ($i = 0 ; $i < (int)$item->getRating() ; $i++)
                {
                    echo "<li class='fa fa-star'></li>";
                }
              }
              ?>
            </ul>
        <?php } ?>
        <?php if ($this->enablePosition() == 1) {?>
            <span class="post"><?php echo $item->getJob(); ?></span>
            <?php }?>
            <?php if ($this->enableSocial() == 1) {?>
            <ul class="social-links">
                <?php if (!empty($item->getTwitter()))
                {
                    echo "<li><a href=".$item->getTwitter()."  target='_blank' class='fab fa-twitter'></a></li>";
                }
                if (!empty($item->getFacebook()))
                {
                    echo "<li><a href=".$item->getFacebook()." target='_blank' class='fab fa-facebook-f'></a></li>";
                }
                if (!empty($item->getLinkedin()))
                {
                    echo "<li><a href=".$item->getLinkedin()." target='_blank' class='fab fa-linkedin'></a></li>";
                }
                if (!empty($item->getYoutube()))
                {
                    echo "<li><a href=".$item->getYoutube()." target='_blank' class='fab fa-youtube'></a></li>";
                }
                if (!empty($item->getVimeo()))
                {
                    echo "<li><a href=".$item->getVimeo()." target='_blank' class='fab fa-vimeo'></a></li>";
                }
                ?>
            </ul>
            <?php } ?>

    <div class="content-heading"><h3 class="testimonial-title"> <?php echo $item->getTitle();  ?></h3></div>
  </div>
  </div>
     <?php
     if ($count%3 == 0)
    {
        echo "</div><div class='container' >";
    }
    $count++;

     }
     if ($count%3 != 1);
     ?>
      </div>

<?php if ($block->getPagerHtml()): ?>
<div class="order-products-toolbar toolbar bottom clearfix ">
<?php echo $block->getPagerHtml(); ?>
</div>
<?php endif ?>
